version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tripper-web-ui
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"