services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tripper-web-ui
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "80:80"